### ISSUE TITLE
Спринт 1. Redux-toolkit добавить нужные модули для его работы

### ISSUE THREAD

**Issue by HanmaDaiki** [StickerStack/StickerStack_frontend#13]

**Comment by cactys** [comment]
Понять бы еще, какие нужные? Сейчас для меня только про поле user и все с ним связанное известно =)

**Comment by HanmaDaiki** [comment]
Ну мы же планируем сначала все сделать пропсами, а потом отрефакторить под редакс, но мы начинаем с авторизации, так что можно просто добавить пока пользователя в редакс
