### ISSUE TITLE
Спринт 1. Баг: исправить видимость глазиков

### ISSUE THREAD

**Issue by Anastacia-Tesli** [StickerStack/StickerStack_frontend#133]
В пустых нетронутых полях сейчас видны глазики. Они должны отображаться только если в поле не менее одного символа

![Image](https://user-images.githubusercontent.com/107041912/230381950-5c2a0976-266d-40a8-b394-fd9d6b5d80e9.png)

![Image](https://user-images.githubusercontent.com/107041912/230382056-c6b518fd-193c-4d21-b825-07759dcc5e0c.png)

**Comment by cactys** [comment]
Это кто-то правил? У меня не отображается просто.
![image](https://user-images.githubusercontent.com/6768072/230552903-1ae893dd-5507-45d2-9084-1ada53d7c9ef.png)
