### ISSUE TITLE
Вынести общие стили интерактивных элементов

### ISSUE THREAD

**Issue by Anastacia-Tesli** [StickerStack/StickerStack_frontend#58]
Нужны отдельные модули (?) стилей для элементов при наведении, чтобы эти свойства были в одном месте и их можно было раз и достать.
А не писать одни и те же ховеры каждый раз.

**Comment by Anastacia-Tesli** [comment]
Предлагаю вынести прямоугольную кнопку с opacity 0.6 при наведении и кнопку/ссылку с подчеркиванием при наведении.

**Comment by HanmaDaiki** [comment]
Идея отличная, ты говоришь про миксин?
