### ISSUE TITLE
Спринт 1. Пофиксить открытие попапа

### ISSUE THREAD

**Issue by Anastacia-Tesli** [StickerStack/StickerStack_frontend#59]
При первом открытии модального окна отображается форма "Войти". Если перейти на другую форму ("Зарегистрироваться или "Забыл пароль") и выйти из модального окна, то при следующем его открытии отображается та форма, которую закрывали.

При открытии всегда должна появляться форма входа.

**Comment by HanmaDaiki** [comment]
Взял
