### ISSUE TITLE
Спринт 1. Разобраться с кастомным чекбоксом

### ISSUE THREAD

**Issue by Anastacia-Tesli** [StickerStack/StickerStack_frontend#60]
- [ ] Чекбокс должен регистрироваться в форме (register)
- [ ] Юридический чекбокс обязательный для отправки формы
- [ ] Стили чекбокса и его псевдоэлемента должны быть выполнены таким образом, чтобы при нажатии срабатывал реальный чекбокс, а также отображалось изменение псевдоэлемента

**Comment by HanmaDaiki** [comment]
взяд
