### ISSUE TITLE
Спринт 1. Добавить логику после авторизации

### ISSUE THREAD

**Issue by Anastacia-Tesli** [StickerStack/StickerStack_frontend#76]
После успешного выполнения запроса на вход пользователя в систему:

- закрывается попап авторизации
- кнопка "Войти" сменяется на иконку с очертаниями человечка (на время тестов - кнопка "Войти" сменяется на кнопку "Выйти")
- кнопка "Попробовать" перебрасывает на новый роут

**Comment by HanmaDaiki** [comment]
Взял. и логику регистрации тоже. В одной ветке
