### ISSUE TITLE
Спринт 1. Баг глазиков в браузере M. Edge

### ISSUE THREAD

**Issue by Anastacia-Tesli** [StickerStack/StickerStack_frontend#89]
Браузер имеет свои дефолтные "глазики", нужно их отключить

![Image](https://user-images.githubusercontent.com/107041912/226553323-e02d31fe-567e-4914-a609-401d8f57194d.png)

**Comment by cactys** [comment]
```css
::-ms-reveal {
    display: none;
}
```

[тынкс](https://learn.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal)

**Comment by cactys** [comment]
забрал )
